import type { Metadata } from "next";
import { Poppins,Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/dashlayout/page";
import ClientSideLayout from "@/components/clientlayout/page";
import RequestPermission from "@/components/requestpermission/page";
import NotificationHandler from "@/components/handlenotification/page";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sensor Data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
        <ClientSideLayout>
          {/* <RequestPermission/> */}
          <NotificationHandler/>
          <Toaster position="top-center" richColors />
        {children}
        </ClientSideLayout>
        </AuthProvider>
        </body>
    </html>
  );
}
