import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/dashlayout/page";
import ClientSideLayout from "@/components/clientlayout/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sensor Data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSideLayout>
        {children}
        </ClientSideLayout>
        </body>
    </html>
  );
}
